package com.test.MySqlConnectorSpringBoot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)

public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private RegistrationRepository registrationRepository;

	
	
	@RequestMapping(
	  value = "/add", 
	  params = { "first", "last","age" }, 
	  method = RequestMethod.GET)
	public @ResponseBody String addNewUser (@RequestParam String first
			, @RequestParam String last,@RequestParam Integer age) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Registration n = new Registration();
		n.setFirst(first);
		n.setLast(last);
		n.setAge(age);
		registrationRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Registration> getAllUsers() {
		// This returns a JSON or XML with the users
		return registrationRepository.findAll();
	}

}
